spring.datasource.url=jdbc:h2:~/sl+;INIT=RUNSCRIPT FROM 'classpath:tables-creation.sql'
#spring.datasource.url=jdbc:h2:/opt/db/sl+;INIT=RUNSCRIPT FROM 'classpath:tables-creation.sql'
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=it
spring.datasource.password=tv13tvhard
spring.data.jpa.repositories.bootstrap-mode=default
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-ui

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jackson.time-zone=America/Argentina/San_Luis
spring.jpa.properties.hibernate.jdbc.time_zone=America/Argentina/San_Luis

jwt.secret=sUdI3HpxjCXjtPrQngVsl6ZAPLQIQp6iSBiXo2arARM/gt67tz98NhHlX5mCZMG+
utils.decrypt=1a3b5d7f9h2j4l6n8p0r2t4v6x8z1A3B
#utils.decrypt=1CetNXIx/bgkPb79KG5iXTqzHDWBGkM5

image.upload.dir=/opt/uploads

spring.web.resources.static-locations=file:/opt/uploads/
